name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish (Framework-dependent, Single File, R2R)
        shell: bash
        run: |
          dotnet publish OpenccNet/OpenccNet.csproj \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --output publish/ \
            --no-self-contained \
            -p:PublishSingleFile=true \
            -p:PublishReadyToRun=true

      - name: Package (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $folder = "OpenccNet-$tag-${{ matrix.rid }}"
          Rename-Item -Path publish -NewName $folder
          Compress-Archive -Path "$folder\*" -DestinationPath "$folder.${{ matrix.ext }}"

      - name: Package (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          tag="${{ github.ref_name }}"
          folder="OpenccNet-$tag-${{ matrix.rid }}"
          mv publish "$folder"
          tar -czf "$folder.${{ matrix.ext }}" "$folder"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenccNet-${{ github.ref_name }}-${{ matrix.rid }}.${{ matrix.ext }}
          path: OpenccNet-${{ github.ref_name }}-${{ matrix.rid }}.${{ matrix.ext }}
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: OpenccNet-*
          merge-multiple: true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: OpenccNet-${{ github.ref_name }}-*
          prerelease: ${{ contains(github.ref_name, '-') }}
          make_latest: ${{ contains(github.ref_name, '-') && 'false' || 'true' }}
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
