name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish ${{ matrix.rid }}
        run: |
          dotnet publish OpenccNet/OpenccNet.csproj \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --self-contained false \
            --output publish-${{ matrix.rid }}

      - name: Archive release
        run: |
          cd publish-${{ matrix.rid }}
          if [ "${{ matrix.ext }}" == "zip" ]; then
            7z a ../OpenccNet-${{ github.ref_name }}-${{ matrix.rid }}.${{ matrix.ext }} *
          else
            tar -czvf ../OpenccNet-${{ github.ref_name }}-${{ matrix.rid }}.${{ matrix.ext }} *
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            OpenccNet-${{ github.ref_name }}-${{ matrix.rid }}.${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
